name: Build and Deploy

on:
   push:
      tags:
         - 'v**'

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         -  uses: actions/checkout@master

         # See: https://stackoverflow.com/a/58178121
         -  name: Set env
            run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

         # See: https://github.com/TheDoctor0/zip-release
         -  name: Archive Release
            uses: thedoctor0/zip-release@master
            with:
               type: 'zip'
               filename: '5etools-${{ env.RELEASE_VERSION }}.zip'
               exclusions: '*.git* /*node_modules/* /*.github/* /*img/*'

         -  name: Add Cache-Busting Strings
            run: |
               bash ./.github/add-query-strings.sh ${{ env.RELEASE_VERSION }}

         -  name: Build SEO Pages
            env:
               VET_BASE_SITE_URL: https://5etools-mirror-1.github.io/
               VET_SEO_IS_SKIP_UA_ETC: true
            run: |
               npm run build:seo -- ${{ env.RELEASE_VERSION }}

         # See: https://github.com/JamesIves/github-pages-deploy-action
         -  name: Deploy
            uses: JamesIves/github-pages-deploy-action@releases/v4
            with:
               branch: gh-pages
               folder: .

         -  name: Archive Images (Adventure)
            uses: thedoctor0/zip-release@master
            with:
               type: 'zip'
               filename: 'img-${{ env.RELEASE_VERSION }}-adventure.zip'
               path: 'img/adventure'

         -  name: Archive Images (Book)
            uses: thedoctor0/zip-release@master
            with:
               type: 'zip'
               filename: 'img-${{ env.RELEASE_VERSION }}-book.zip'
               path: 'img/book'

         -  name: Archive Images (Cleanup)
            run: 'rm -rf img/adventure img/book'

         -  name: Archive Images (Other)
            uses: thedoctor0/zip-release@master
            with:
               type: 'zip'
               filename: 'img-${{ env.RELEASE_VERSION }}.zip'
               path: 'img'

         -  name: Upload Release
            # Add the files one-by-one in an effort to avoid timeouts
            run: |
               hub release create -a 5etools-${{ env.RELEASE_VERSION }}.zip -m ${{ env.RELEASE_VERSION }} ${{ env.RELEASE_VERSION }}
               hub release edit ${{ env.RELEASE_VERSION }} -m '' -a img-${{ env.RELEASE_VERSION }}.zip
               hub release edit ${{ env.RELEASE_VERSION }} -m '' -a img-${{ env.RELEASE_VERSION }}-book.zip
               hub release edit ${{ env.RELEASE_VERSION }} -m '' -a img-${{ env.RELEASE_VERSION }}-adventure.zip
            env:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
