name: Build and Deploy

on:
   push:
      tags:
         - 'v**'

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         -  uses: actions/checkout@master

         # See: https://stackoverflow.com/a/58178121
         -  name: Set env
            run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

         # region See: https://github.com/TheDoctor0/zip-release
         -  name: Archive Release
            uses: thedoctor0/zip-release@master
            with:
               type: 'zip'
               filename: '5etools-${{ env.RELEASE_VERSION }}.zip'
               exclusions: '*.git* /*node_modules/* /*.github/* /*img/*'

         -  name: Archive Images
            uses: thedoctor0/zip-release@master
            with:
               type: 'zip'
               filename: 'img-${{ env.RELEASE_VERSION }}.zip'
               path: 'img'

         - name: List Files
           run: |
           ls -lah
           ls -lah img

         -  name: Upload Release
            run: 'hub release create -a 5etools-${{ env.RELEASE_VERSION }}.zip -a img-${{ env.RELEASE_VERSION }}.zip -m ${{ env.RELEASE_VERSION }} ${{ env.RELEASE_VERSION }}'
            env:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         # endregion

         - name: Build SEO Pages
           env:
              VET_SEO_IS_DEV_MODE: true
              VET_BASE_SITE_URL: https://5etools-mirror-1.github.io/
              VET_SEO_IS_SKIP_UA_ETC: true
           run: |
              npm run build:seo

         # See: https://github.com/JamesIves/github-pages-deploy-action
         - name: Deploy
           uses: JamesIves/github-pages-deploy-action@releases/v4
           with:
              branch: gh-pages
              folder: .
